# Generated by Django 5.1.7 on 2025-03-28 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0002_initial'),
        ('section', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='section.section'),
        ),
    ]
