# Generated by Django 5.1.7 on 2025-03-21 12:33

import receipt.common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0002_receiptitemcategory_receipt_receiptitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='taxpayer_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='photo',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=receipt.common.get_photo_upload_path),
        ),
    ]
