# Generated by Django 5.1.7 on 2025-04-06 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0003_receipt_section'),
        ('section', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptitemcategory',
            name='color',
            field=models.CharField(default='#ffffff', max_length=34),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='section.section'),
        ),
    ]
