# Generated by Django 5.1.7 on 2025-03-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0003_shop_taxpayer_id_alter_receipt_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
