# Generated by Django 5.2 on 2025-04-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0004_receiptitemcategory_color_alter_receipt_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
