# Generated by Django 5.2 on 2025-04-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0005_receipt_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='date_last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
