# Generated by Django 5.1.7 on 2025-03-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0005_alter_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
