# Generated by Django 5.2 on 2025-04-20 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0006_receipt_date_add_receipt_date_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='ReceiptItemCategory',
        ),
    ]
