# Generated by Django 5.2 on 2025-04-20 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0008_receiptitemcategory_receiptitemcategorytranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receipt.receiptitemcategory'),
        ),
    ]
