# Generated by Django 5.2 on 2025-04-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0009_receiptitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='input_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
