# Generated by Django 5.2 on 2025-04-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantranslation',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
