# Generated by Django 5.2 on 2025-04-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_plantranslation_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
