# Generated by Django 5.1.7 on 2025-03-11 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
        ('section', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_section', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectionuser',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.currency'),
        ),
        migrations.AddField(
            model_name='sectionuser',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.section'),
        ),
        migrations.AddField(
            model_name='sectionuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='sections', through='section.SectionUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sectionuser',
            unique_together={('user', 'section')},
        ),
    ]
