# Generated by Django 5.1.7 on 2025-03-27 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
        ('section', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionuser',
            name='currency',
            field=models.ForeignKey(default=150, on_delete=django.db.models.deletion.CASCADE, to='currency.currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sectionuser',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='section.section'),
        ),
    ]
