# Generated by Django 5.2 on 2025-04-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionuser',
            name='user_section_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
