# Generated by Django 5.2 on 2025-04-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_feedback_feedbackreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('es', 'Español')], default='en-us', help_text='Выберите предпочитаемый язык интерфейса', max_length=10, verbose_name='Язык пользователя'),
        ),
    ]
