# Generated by Django 5.2 on 2025-04-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('es', 'Español')], default='en', max_length=10, verbose_name='Language'),
        ),
    ]
