# Generated by Django 5.1.7 on 2025-03-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aiusagelog',
            table='ai_usage_log',
        ),
    ]
