# Generated by Django 5.2 on 2025-04-23 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receipt', '0009_receiptitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptStatusMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('processed', 'Processed'), ('error', 'Error')], default='in_progress', max_length=255, verbose_name='Status')),
                ('chat_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='receipt.receipt')),
            ],
        ),
    ]
