# Generated by Django 5.2 on 2025-04-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('chat_id', models.BigIntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('invoice_payload', models.TextField()),
                ('total_amount', models.PositiveIntegerField()),
                ('telegram_payment_charge_id', models.CharField(max_length=255, unique=True)),
                ('provider_payment_charge_id', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('successful', 'Successful')], default='successful', max_length=20)),
                ('subscription_expiration_date', models.PositiveIntegerField(blank=True, null=True)),
                ('is_first_recurring', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PreCheckoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('pre_checkout_query_id', models.CharField(max_length=255)),
                ('invoice_payload', models.TextField()),
                ('total_amount', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
